# Generated by Django 2.1.2 on 2018-10-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Address',
            field=models.CharField(default='shastri park', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='rj33536@gmail.com', max_length=254),
        ),
    ]
