# Generated by Django 2.1.2 on 2018-10-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20181018_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='myproduct',
            field=models.IntegerField(default=1),
        ),
    ]
