# Generated by Django 3.0.2 on 2020-03-29 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0005_order_myproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart',
            field=models.ManyToManyField(related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
